name: Scheduled Model Training

on:
  schedule:
    - cron: '50 * * * *'  # every hour at :50 (UTC)
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies manually
        run: |
          pip install --no-cache-dir \
            confluent-kafka \
            duckdb \
            joblib \
            jupyter \
            lightgbm \
            matplotlib \
            optuna \
            pandas \
            plotly \
            pyarrow \
            python-dotenv \
            quixstreams \
            scikit-learn \
            streamlit \
            TA-Lib \
            websockets

      - name: Run training script
        run: |
          python services/train/train.py
