name: Scheduled Model Training

on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install TA-Lib system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir \
            confluent-kafka \
            duckdb \
            joblib \
            jupyter \
            lightgbm \
            matplotlib \
            optuna \
            pandas \
            plotly \
            pyarrow \
            python-dotenv \
            quixstreams \
            scikit-learn \
            streamlit \
            TA-Lib \
            websockets

      - name: Run training script
        run: |
          python services/train/train.py
